### ISSUE TITLE
是否支持jsx

### ISSUE THREAD

**Issue by Zen33** [yuekcc/esbuild-plugin-vue2-template-compiler#1]
esbuild 的 jsxFactory 默认为React，当前的plugin是否能解决该问题？谢谢。

**Comment by yuekcc** [comment]
没有。这个插件只用于处理 vue template 标签代码。jsxFactory 应该可以配置为 vue 的 h 函数。

完整的 .vue 文件支持可以看看 https://www.npmjs.com/package/esbuild-vue。

**Comment by Zen33** [comment]
Vue2.x目前应该是无解了，不过还是多谢。
